language:
    - java

services:
    - mysql

jdk:
    - oraclejdk8

before_install:
    - mysql -u root < initialize.sql

script:
    - mvn exec:java -Dexec.mainClass="utilities.PopulateDatabase"
    - mvn clean test
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.organization=shipmee
    - ls -lah

after_success:
  - mvn clean cobertura:cobertura coveralls:report -DrepoToken=$tokenCoverall

cache:
    directories:
        - $HOME/.m2   # Cache para las dependencias de maven
        - '$HOME/.sonar/cache' # Cache para sonar

addons:
    sonarqube:
        token:  # encrypted value of your token
            secure: "UkW0I83nifb5EyWR6Dou1zZz5i6riWa2EDgTgqfiB/YqYtrfoz2zwnVFxO+62ACUGbQfkLanv7pxZmgBfYZRR5TNndG6fiiB7lylKkRYksfik9BN2hDj1AxxBbhB0fiuCT5N6gF8QC/tkGmhESff11Ytb2RJHIG8cql5IKMjzXi/txYs85npIE5775B9nWmKznpsRVeXCAvnIjnDfD7wJDZUvgP901zIjKwEwxLuraH1q1xLwj/O102Q8VLklnkH18USaqEs8O7+XHhUTjOLwOp4pvv3Droyh/JeAHrLOdAUwhB4GmPkoQCdD706LH9PCAntD+MoyG4kcecgzf0DV/O7ZgknD/+DV6pJ9XCjVdfsUhoml2+DeEorodScXDByN4weLb7JIWasKZLERV5mTjquiRKdn2NC7DhFebf0shQNVXjBAX3xqJk62vLEEyHfMsCGETA0zw5Ps8j4BkKV6Xb+By06yDUFCSL80WSb/pqR3RRzOthOJhTJzksXm4WECACV1GT5McN8M4tWD/6FZVQqGG6b8FLbG0IyBM86TwWIlJ2RaTyiOHHB6RP5llkTdQQ+L9CIa54+P7vN9eRcj9XYXAPlKCyudFUBpnO9gYZVX2FRI45Ip21KCOCMY3RziJ6iTa04CoIDVopZIDM5WjcF7m7EsNDuqHmADLuz21Q="
        branches:
            - integrations
            - develop
            - master

dist:
    - trusty

sudo:
    - false

notifications:
- email: false  # Desactivamos las notificaciones por email para evitar spam 
 
