language:
    - java

services:
    - mysql

jdk:
    - oraclejdk8

before_install:
    - mysql -u root < initialize.sql

script:
    - mvn exec:java -Dexec.mainClass="utilities.PopulateDatabase"
    - mvn clean test
    - ls -lah

cache:
    directories:
        - $HOME/.m2   # Cache para las dependencias de maven

dist:
    - trusty

sudo:
    - false

notifications:
- email: false  # Desactivamos las notificaciones por email para evitar spam 
 
